language: node_js
node_js:
  - "4"
# node_js 4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8"
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
# for some reason we have to re-install mongoose to run the tests, ugh.
before_script: npm install mongoose@3.8.40
script: npm run test:coverage:check
after_script: npm run coveralls
